INSERT INTO app_user (username, mail) VALUES
('test', 'test@test.com'),
('string', 'string@string.com'),
('example', 'example@example.com');

INSERT INTO task (title, description, status, created_at, updated_at) VALUES
('Grocery shopping', 'Buy milk, tea, coffee', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Write report', 'Finish Q3 financial summary', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fix login bug', 'Resolve OAuth NullPointerException', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Plan sprint', 'Prepare backlog and estimates', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refactor service', 'Split mapping logic into helper class', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Update README', 'Add project description and usage guide', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Team meeting', 'Discuss project milestones', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Implement login', 'Add JWT authentication', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Database backup', 'Schedule daily backup job', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Review PR #42', 'Code review for new feature branch', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Deploy to staging', 'Push latest build to staging server', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Design API docs', 'Write Swagger annotations', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Research caching', 'Evaluate Redis integration', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Optimize query', 'Improve performance of report endpoint', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bug triage', 'Classify open GitHub issues', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Shopping list', 'Buy vegetables and fruits', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Morning workout', '30 min cardio and stretching', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Read book', 'Continue reading Clean Code', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Setup CI', 'Add GitHub Actions pipeline', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Configure Docker', 'Write Dockerfile for backend', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fix CSS', 'Correct button alignment', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Buy birthday gift', 'Get present for Sarah', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Email client', 'Send project update', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pay bills', 'Electricity and water payment', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Clean desk', 'Organize workspace', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refactor tests', 'Improve unit test coverage', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Update dependencies', 'Bump Spring Boot version', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Plan holiday', 'Check flights and hotels', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Organize photos', 'Clean up Google Drive albums', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Water plants', 'Living room and balcony plants', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Meditation', '10 minutes daily meditation', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Learn Docker', 'Follow online tutorial', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Prepare slides', 'Presentation for Monday meeting', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fix search bug', 'Results not sorted properly', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Add logging', 'Integrate SLF4J and Logback', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Polish UI', 'Improve navbar styling', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Doctor appointment', 'Annual health check', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Car service', 'Oil change and inspection', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Weekly review', 'Reflect on goals and progress', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cook dinner', 'Pasta with salad', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refactor repo', 'Split modules into separate repos', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Test API', 'Postman regression tests', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Update wiki', 'Add troubleshooting guide', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Brainstorm', 'Ideas for new side project', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('File taxes', 'Prepare documents', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Laundry', 'Wash and fold clothes', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Plan meetup', 'Organize team dinner', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Check emails', 'Inbox zero routine', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);